version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
configuration: Release
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
